# Generated by Django 3.0 on 2021-01-28 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_question_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixes',
            name='abuse',
            field=models.BooleanField(default=False),
        ),
    ]
